\copy venues(venue_name, capacity, grass, indoor, city, state) from '../../data/venues.csv' DELIMITER ',' CSV HEADER;
\copy teams(location, team_name, abbreviation, primary_color, secondary_color, venue_name) from '../../data/teams.csv' DELIMITER ',' CSV HEADER;
\copy positions(position_name, abbreviation, platoon) from '../../data/positions.csv' DELIMITER ',' CSV HEADER;
\copy athletes(athlete_id, first_name, last_name, height, weight, dob, birth_city, birth_state) from '../../data/athletes_split.csv' DELIMITER ',' CSV HEADER;
\copy season_dates(date, season_year, season_type, week) from '../../data/season_dates.csv' DELIMITER ',' CSV HEADER;
\copy games(game_id, date, attendance, utc_time, venue_name, home_team, away_team) from '../../data/games.csv' DELIMITER ',' CSV HEADER;
\copy rosters(game_id, athlete_id, played, team_name, position_name) from '../../data/rosters.csv' DELIMITER ',' CSV HEADER;
\copy plays(play_id, start_down, end_down, quarter, play_type, seconds_remaining, text, score_value, yards) from '../../data/full_plays.csv' DELIMITER ',' CSV HEADER;
\copy player_plays(play_id, game_id, player_id, type) from '../../data/full_player_plays.csv' DELIMITER ',' CSV HEADER;
\copy linescores(game_id, quarter, score, team_name) from '../../data/linescores.csv' DELIMITER ',' CSV HEADER;